feeds:
  cctv-1:
    camera:
      params:
        camera_name: '0'
        vehicle_name: Drone2
      type: airsim
    fov: 90
    location: Aerial Overview
    name: CCTV CAM 1
    orientation:
      pitch: 0
      roll: 0
      yaw: 0
    position:
      altitude: 10
      latitude: 10
      longitude: 10
    scene_type: bridge
  cctv-2:
    camera:
      params:
        camera_name: '0'
        vehicle_name: Drone3
      type: airsim
    location: Aerial Overview
    name: CCTV CAM 2
    scene_type: bridge
  cctv-3:
    camera:
      params:
        camera_name: '0'
        vehicle_name: Drone4
      type: airsim
    location: Aerial Overview
    name: CCTV CAM 3
    scene_type: bridge
  cctv-4:
    camera:
      params:
        camera_name: '0'
        vehicle_name: Drone5
      type: airsim
    location: Aerial Overview
    name: CCTV CAM 4
    scene_type: bridge
